server:
  port: 8004
spring:
  profiles:
    active: local
---
spring:
  application:
    name: gateway-server
  cloud:
    config:
      discovery:
        enabled: true # 通过服务发现的方式去找配置中心
        service-id: config-server
      profile: local
eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port} #注册到eureka时显示服务的名称，ip，端口
    prefer-ip-address: true
      # 实际注册地址，每个服务各不相同，要看该服务在哪个服务器上
    ip-address: ${eureka.instance.hostname}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zhaolaobao:wd2fWNSh2ijLcsKcgXgA98zIbOJEB8m7WgeU8mRj5hrsl2EfIv@localhost:8001/eureka/

