server:
  port: 8004
spring:
  application:
    name: gateway-server #指定配置文件的应用名称

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
    # 更改eureka更新频率, 关闭eureka的自我保护机制.
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://zhaolaobao:wd2fWNSh2ijLcsKcgXgA98zIbOJEB8m7WgeU8mRj5hrsl2EfIv@localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true

#  redis:
#    host: server-b-3
#    port: 6379
#    password: FqJe3AiDkP$q
#    database: 11
#    timeout: 10000 # 连接超时时间（毫秒）
#    pool:
#      maxIdle: 20   #最大空闲连接数
#      minIdle: 8   #最小空闲连接数
#      maxActive: 300   # 连接池最大连接数（使用负值表示没有限制）
#      maxWait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
zuul:
  # 公共前缀
  # prefix: /api
  # 路由转发规则
  routes:
    authority:
      path: /**
      sensitiveHeaders:
      service-id: authority-server
    product:
      path: /**
      sensitiveHeaders:
      service-id: product-server
    usercenter:
      path: /**
      sensitiveHeaders:
      service-id: usercenter-server
