server:
  port: 8005
spring:
  application:
    name: product-server #指定配置文件的应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.25.67:26535/qs_3.0_product?characterEncoding=utf8
    username: root
    password: nYZGy6mz

#  cloud:
#    config:
#      server:
#        bootstrap=true:
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
    # 更改eureka更新频率, 关闭eureka的自我保护机制.
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://zhaolaobao:wd2fWNSh2ijLcsKcgXgA98zIbOJEB8m7WgeU8mRj5hrsl2EfIv@localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true

mybatis:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml