spring:
  redis:
    host: 121.40.245.250
    port: 6379
    password: FqJe3AiDkP$q
    database: 0
    timeout: 1000 # 连接超时时间（毫秒）
    pool:
      maxIdle: 20   #最大空闲连接数
      minIdle: 8   #最小空闲连接数
      maxActive: 300   # 连接池最大连接数（使用负值表示没有限制）
      maxWait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）