spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.25.67:26535/qs_3.0_product?characterEncoding=utf8
    username: root
    password: nYZGy6mz
mybatis:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml