server:
  port: 8003
spring:
  application:
      name: authority-server #指定配置文件的应用名称


  main:
    allow-bean-definition-overriding: true


eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
    # 更改eureka更新频率, 关闭eureka的自我保护机制.
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://zhaolaobao:wd2fWNSh2ijLcsKcgXgA98zIbOJEB8m7WgeU8mRj5hrsl2EfIv@localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
  redis:
    host: 192.168.254.131:6379
zlb:
  authorization: Basic d2ViOndlYi1zZWNyZXQ=
  grant-type: password
